title:              Eudenia Makeup
email:              
description:        
author:             Kelly Eudenia
baseurl:            "/eudeniamakeup.github.io"
url:                "https://www.vagnerbarbosa.com/eudeniamakeup.github.io"

# Social Profiles
twitter_username:   
github_username:    
facebook_username:  eudeniamakeup-102826581224859
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
